Update to have chef-client run under Bluepill on the computer nodes.

diff --git a/chef/cookbooks/ubuntu-install/templates/default/crowbar_join.sh.erb b/chef/cookbooks/ubuntu-install/templates/default/crowbar_join.sh.erb
--- a/chef/cookbooks/ubuntu-install/templates/default/crowbar_join.sh.erb
+++ b/chef/cookbooks/ubuntu-install/templates/default/crowbar_join.sh.erb
@@ -99,23 +99,69 @@ final_state="ready"
 mkdir -p /etc/chef
 wget -q "http://$HTTP_SERVER/validation.pem" -O- > /etc/chef/validation.pem
 
-# Install Chef
-echo "Installing Chef..."
-echo "chef chef/chef_server_url string http://$IP:4000" >/tmp/debsel.conf
+if [[ ! -x /etc/init.d/bluepill ]]; then
+    # Install Chef
+    echo "Installing Chef..."
+    echo "chef chef/chef_server_url string http://$IP:4000" >/tmp/debsel.conf
 
-while ! log_to apt /usr/bin/apt-get update ; do
-  echo "Failed to apt-get update, wait and try again"
-  sleep 1
-done
-log_to apt /usr/bin/debconf-set-selections /tmp/debsel.conf
-while ! log_to apt /usr/bin/apt-get --force-yes -y install chef ; do
-  echo "Failed to apt-get install, wait and try again"
-  sleep 1
-done
+    while ! log_to apt /usr/bin/apt-get update ; do
+	echo "Failed to apt-get update, wait and try again"
+	sleep 1
+    done
+    log_to apt /usr/bin/debconf-set-selections /tmp/debsel.conf
+    while ! log_to apt /usr/bin/apt-get --force-yes -y install chef ; do
+	echo "Failed to apt-get install, wait and try again"
+	sleep 1
+    done
 
-log_to chef service chef-client stop
-log_to chef killall chef-client
+    # Disable the chef-client service and make it not executable.
+    log_to chef service chef-client stop
+    log_to chef killall chef-client
+    log_to chef update-rc.d chef-client disable
+    log_to chef chmod ugo-x /etc/init.d/chef-client
 
+    # Make sure that gem-installed binaries are in $PATH for everyone.
+    read gem_bin < <(gem environment | awk '-F:' '/EXECUTABLE DIRECTORY/ {print $2}')
+    if [[ ! $PATH =~ (^|:)$gem_bin(:|$) ]]; then
+	export PATH="$PATH:$gem_bin"
+	echo $PATH
+	sed -i "/PATH=/ s@PATH=.*@PATH=\"$PATH\"@" /etc/environment
+	echo "PATH=\"$PATH\"" >/etc/environment
+    fi
+
+    # Fix up our gem sources and install bluepill
+    gem source -a "http://$IP:3001/"
+    gem source -r http://rubygems.org/
+    gem install bluepill
+    mkdir -p /etc/bluepill
+    curl -o /etc/bluepill/chef-client.pill http://$IP:3001/chef-client.pill
+    # Create an init script for bluepill
+    cat > /etc/init.d/bluepill <<EOF
+#!/bin/bash
+# chkconfig: 2345 10 90
+# description: Bluepill Daemon runner
+PATH=$PATH
+case \$1 in
+    start) for pill in /etc/bluepill/*.pill; do
+              [[ -f \$pill ]] || continue
+              bluepill load "\$pill"
+           done;;
+    stop) bluepill stop
+          bluepill quit;;
+    status) if pidof bluepilld; then
+             echo "Bluepill is running."
+             exit 0
+            else
+             echo "Bluepill is not running."
+             exit 1
+            fi;;
+    *) echo "\$1: Not supported.";;
+esac   
+EOF
+    chmod 755 /etc/init.d/bluepill
+fi
+
+    
 # Run Chef
 echo "Syncing time (pass 2)"
 sync_time
@@ -176,8 +222,7 @@ log_to apt apt-get -q --force-yes -y upgrade
 post_state $HOSTNAME "$final_state"
 
 log_to time service ntp start
-# Chef client restart / start aren't implemented quite right.  So make sure we really start the chef-client fresh
-log_to chef service chef-client stop
-log_to chef service chef-client start
+# Fire up bluepill, and let it keep chef-client up.
+service bluepill start
 
 echo "Done"
